# Generated by Django 3.1.4 on 2021-03-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210303_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photo',
        ),
    ]
